import React from 'react';
import Table from 'data-tables-react';

function EmployeesTable() {
  return (
    <div>
      <Table
        data={[
          {
            id: 1,
            firstName: 'John',
            lastName: 'Doe',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 2,
            firstName: 'Jane',
            lastName: 'Doe',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 3,
            firstName: 'Joe',
            lastName: 'Bloggs',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 4,
            firstName: 'Jane',
            lastName: 'Bloggs',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 5,
            firstName: 'Joe',
            lastName: 'Smith',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 6,
            firstName: 'Jane',
            lastName: 'Smith',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 7,
            firstName: 'Joe',
            lastName: 'Jones',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 8,
            firstName: 'Jane',
            lastName: 'Jones',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 9,
            firstName: 'Joe',
            lastName: 'Williams',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 10,
            firstName: 'Jane',
            lastName: 'Williams',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 11,
            firstName: 'Joe',
            lastName: 'Brown',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 12,
            firstName: 'Jane',
            lastName: 'Brown',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 13,
            firstName: 'Joe',
            lastName: 'Miller',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 14,
            firstName: 'Jane',
            lastName: 'Miller',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 15,
            firstName: 'Joe',
            lastName: 'Davis',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 16,
            firstName: 'John',
            lastName: 'Doe',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 17,
            firstName: 'Jane',
            lastName: 'Doe',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 18,
            firstName: 'Joe',
            lastName: 'Bloggs',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 19,
            firstName: 'Jane',
            lastName: 'Bloggs',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 20,
            firstName: 'Joe',
            lastName: 'Smith',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 21,
            firstName: 'Jane',
            lastName: 'Smith',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 22,
            firstName: 'Joe',
            lastName: 'Jones',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 23,
            firstName: 'Jane',
            lastName: 'Jones',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 24,
            firstName: 'Joe',
            lastName: 'Williams',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 25,
            firstName: 'Jane',
            lastName: 'Williams',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 26,
            firstName: 'Joe',
            lastName: 'Brown',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 27,
            firstName: 'Jane',
            lastName: 'Brown',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 28,
            firstName: 'Joe',
            lastName: 'Miller',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 29,
            firstName: 'Jane',
            lastName: 'Miller',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 30,
            firstName: 'Joe',
            lastName: 'Davis',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 31,
            firstName: 'Joe',
            lastName: 'Miller',
            startDate: '2015-01-01',
            department: 'Sales',
            dateOfBirth: '1980-01-01',
            street: '3 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '1',
          },
          {
            id: 32,
            firstName: 'Jane',
            lastName: 'Miller',
            startDate: '2016-02-01',
            department: 'Sales',
            dateOfBirth: '1982-08-12',
            street: '123 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '90210',
          },
          {
            id: 33,
            firstName: 'Joe',
            lastName: 'Davis',
            startDate: '2016-01-01',
            department: 'Sales',
            dateOfBirth: '1982-08-13',
            street: '23 Main Street',
            city: 'Anytown',
            state: 'CA',
            zipCode: '902100000',
          },
        ]}
      />
    </div>
  );
}

export default EmployeesTable;
